### ISSUE TITLE
Изготовить плату питания

### ISSUE THREAD

**Issue by Alexpechonov** [Lipotam/trackPlatform#40]
**Задача:** изготовить плату питания, спроектированную в issue #39.
**На выходе получить:** полностью готовую к подключению плату питания.

**Comment by Alexpechonov** [comment]
Выполнение доступно после завершения задачи #39

**Comment by YuraStr** [comment]
Плата изготовлена.

**Comment by Lipotam** [comment]
Не все разъемы припаяны на плату

**Comment by AJIOB** [comment]
Issue перенесена (#63)
