### ISSUE TITLE
Подключение модуля Wi-Fi.

### ISSUE THREAD

**Issue by MikhailLU** [Lipotam/trackPlatform#5]
**Задача:** подключить модуль Wi-Fi к танку.
**На выходе получить:** танк с возможностью управления через Wi-Fi.

- [x] Изучение работы модуля wi-fi
- [ ] Подключение модуля wi-fi к танку
- [ ] Тестирование взаимодействия wi-fi модуля с танком
- [ ] Интегрирование работы wi-fi модуля в API

**Comment by AJIOB** [comment]
Issue дублирует #67
